export const gameState = {
    unitSize: 25,
    isRunning: true,
    lastTime: 0,
    accumulator: 0,
    gameSpeed: 1000 / 10,
    direction: { x: 1, y: 0 },
    nextDirection: { x: 1, y: 0 },
    score: 0,
    lastTailPosition: null,
    wallCollision: true,
};

export const modeState = {
    modeSelected: "normal",
    normal: true,
    hard: true,
    expert: true,
    master: false,
    inferno: false,
};

export const foodState = {
    eatenFoodPositions: [],
    currentSpecialFood: null,       //WHAT FOOD IS CHOSEN
    specialFoodSpawnTimer: 3000,    //TIMER BEFORE FUNCTION CALL

    foods: [
        {
            id: "apple",
            isSpecial: false,
            locked: false,
            spawnChance: 100,
            timer: 0,
            position: null,
            visible: true,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 1, hard: 2, expert: 3, master: 4, inferno: 5 },
        },
        {
            id: "carrot",
            isSpecial: true,
            locked: false,
            spawnChance: 100,
            timer: 5000,
            position: null,
            visible: false,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 3, hard: 6, expert: 9, master: 12, inferno: 15 },
        },
        {
            id: "banana",
            isSpecial: true,
            locked: false,
            spawnChance: 25,
            timer: 4000,
            position: null,
            visible: false,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 9, hard: 18, expert: 27, master: 36, inferno: 45 },
        },
        {
            id: "apricot",
            isSpecial: true,
            locked: true,
            spawnChance: 15,
            timer: 4000,
            position: null,
            visible: false,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 18, hard: 36, expert: 54, master: 62, inferno: 90 },
        },
        {
            id: "watermelon",
            isSpecial: true,
            locked: true,
            spawnChance: 10,
            timer: 3000,
            position: null,
            visible: false,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 20, hard: 40, expert: 60, master: 80, inferno: 100 },
        },
        {
            id: "avocado",
            isSpecial: true,
            locked: true,
            spawnChance: 5,
            timer: 3000,
            position: null,
            visible: false,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 18, hard: 36, expert: 54, master: 62, inferno: 90 },
        },
    ],
};
