export const gameState = {
    unitSize: 25,
    isRunning: true,
    lastTime: 0,
    accumulator: 0,
    gameSpeed: 1000 / 10,
    direction: { x: 1, y: 0 },
    nextDirection: { x: 1, y: 0 },
    inputBuffer: [],
    maxInputBuffer: 2,
    score: 0,
    lastTailPosition: null,
    wallCollision: true,
    perksUnlocked: false,
    isWaitingForReset: false,
};

export const modeState = {
    modeSelected: "normal",
    modes: {
        normal: { unlocked: true },
        hard: { unlocked: false },
        expert: { unlocked: false },
        master: { unlocked: false },
        inferno: { unlocked: false },
    },
};

export const foodState = {
    eatenFoodPositions: [],
    currentSpecialFood: null,
    specialFoodSpawnTimer: 10000, //First spawn
    doubleRewardTimeLeft: 0,

    foods: [
        {
            id: "apple",
            isSpecial: false,
            unlocked: true,
            spawnChance: 100,
            timer: 0,
            position: null,
            visible: true,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 1, hard: 2, expert: 3, master: 4, inferno: 5 },
        },
        {
            id: "carrot",
            isSpecial: true,
            unlocked: false,
            spawnChance: 100,
            timer: 4000,
            position: null,
            visible: false,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 3, hard: 6, expert: 9, master: 12, inferno: 15 },
        },
        {
            id: "banana",
            isSpecial: true,
            unlocked: false,
            spawnChance: 25,
            timer: 4000,
            position: null,
            visible: false,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 8, hard: 16, expert: 32, master: 48, inferno: 64 },
        },
        {
            id: "apricot",
            isSpecial: true,
            unlocked: false,
            spawnChance: 15,
            timer: 4000,
            position: null,
            visible: false,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 15, hard: 30, expert: 45, master: 60, inferno: 75 },
        },
        {
            id: "watermelon",
            isSpecial: true,
            unlocked: false,
            spawnChance: 10,
            timer: 3000,
            position: null,
            visible: false,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 22, hard: 44, expert: 66, master: 88, inferno: 110 },
        },
        {
            id: "avocado",
            isSpecial: true,
            unlocked: false,
            spawnChance: 5,
            timer: 3000,
            position: null,
            visible: false,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 30, hard: 60, expert: 90, master: 120, inferno: 150 },
        },
    ],
};
